#!/usr/bin/env python3
"""Measure the GOOSE 3D validation split and write the R2 Markdown report.

The script streams one frame at a time, so memory use is bounded by the largest
point cloud rather than the whole split.

    python scripts/goose_stats.py --root C:\goose\goose_3d_val
"""

import argparse
import csv
from datetime import date
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from goose_render_frame import find_frames, load_frame  # noqa: E402


REPO = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO / "GOOSE - Ricky+Damien" / "dataset-statistics.md"
RANGE_LABELS = ("0–25 m", "25–50 m", "50–100 m", "100–150 m", "150 m+")
RANGE_BINS = np.array([0.0, 25.0, 50.0, 100.0, 150.0, np.inf])


def load_classes(root):
    mapping = pathlib.Path(root) / "goose_label_mapping.csv"
    with mapping.open(newline="", encoding="utf-8-sig") as fh:
        rows = list(csv.DictReader(fh))
    return {int(row["label_key"]): row["class_name"] for row in rows}


def pct(value, total):
    return f"{100.0 * value / total:.4f}%" if total else "0.0000%"


def scenario_name(scan_path):
    return scan_path.parent.name


def measure(root):
    classes = load_classes(root)
    max_id = max(classes)
    frames = find_frames(root)
    class_counts = np.zeros(max_id + 1, dtype=np.int64)
    range_counts = np.zeros(len(RANGE_LABELS), dtype=np.int64)
    scenario_counts = {}
    scenario_points = {}
    points_per_frame = []

    for index, (scan, label) in enumerate(frames, start=1):
        points, sem = load_frame(scan, label)
        name = scenario_name(scan)
        counts = np.bincount(sem, minlength=max_id + 1)[:max_id + 1]
        class_counts += counts
        scenario_counts.setdefault(
            name, np.zeros(max_id + 1, dtype=np.int64)
        )
        scenario_counts[name] += counts
        scenario_points.setdefault(name, []).append(len(points))
        points_per_frame.append(len(points))

        radius = np.hypot(points[:, 0], points[:, 1])
        range_counts += np.histogram(radius, bins=RANGE_BINS)[0]

        if index % 100 == 0 or index == len(frames):
            print(f"Processed {index}/{len(frames)} frames", flush=True)

    return {
        "classes": classes,
        "frames": frames,
        "class_counts": class_counts,
        "range_counts": range_counts,
        "scenario_counts": scenario_counts,
        "scenario_points": scenario_points,
        "points_per_frame": np.asarray(points_per_frame, dtype=np.int64),
    }


def write_report(result, out_path, generated_on=None):
    generated_on = generated_on or date.today()
    generated_date = f"{generated_on.day} {generated_on.strftime('%B %Y')}"
    classes = result["classes"]
    counts = result["class_counts"]
    total = int(counts.sum())
    scenarios = sorted(result["scenario_counts"])
    frame_points = result["points_per_frame"]
    effectively_absent = [
        key for key in classes if counts[key] / total < 0.0001
    ]

    lines = [
        "# GOOSE validation-split statistics",
        "",
        f"Generated by `scripts/goose_stats.py` on {generated_date} from the current "
        "downloadable GOOSE 3D validation archive.",
        "",
        "## Method",
        "",
        f"- {len(result['frames']):,} paired LiDAR/label frames across "
        f"{len(scenarios)} scenarios",
        f"- {total:,} labelled points in total",
        "- Class shares use the full 64-class `goose_label_mapping.csv` taxonomy.",
        "- Radial range is horizontal distance from the ego sensor, "
        "`sqrt(x² + y²)`; z is deliberately excluded.",
        "- ‘Effectively absent’ means less than 0.01% of all labelled points.",
        "",
        "## 1. Class frequency across the split",
        "",
        "| ID | Class | Points | Share |",
        "|---:|---|---:|---:|",
    ]
    for key in sorted(classes, key=lambda k: (-counts[k], k)):
        lines.append(
            f"| {key} | {classes[key]} | {int(counts[key]):,} | "
            f"{pct(int(counts[key]), total)} |"
        )

    lines.extend([
        "",
        "## 2. Per-scenario class distribution",
        "",
        "Each cell is the class share within that scenario. This is a distribution "
        "table, not a performance comparison.",
        "",
        "| ID / class | " + " | ".join(scenarios) + " |",
        "|---|" + "---:|" * len(scenarios),
    ])
    for key in sorted(classes):
        cells = []
        for name in scenarios:
            scenario_total = int(result["scenario_counts"][name].sum())
            cells.append(pct(int(result["scenario_counts"][name][key]), scenario_total))
        lines.append(f"| {key} — {classes[key]} | " + " | ".join(cells) + " |")

    lines.extend([
        "",
        "## 3. Points per frame",
        "",
        "| Scope | Frames | Min | Max | Mean | Median |",
        "|---|---:|---:|---:|---:|---:|",
        f"| Whole split | {len(frame_points):,} | {int(frame_points.min()):,} | "
        f"{int(frame_points.max()):,} | {frame_points.mean():,.1f} | "
        f"{np.median(frame_points):,.1f} |",
    ])
    for name in scenarios:
        values = np.asarray(result["scenario_points"][name])
        lines.append(
            f"| {name} | {len(values):,} | {int(values.min()):,} | "
            f"{int(values.max()):,} | {values.mean():,.1f} | "
            f"{np.median(values):,.1f} |"
        )

    lines.extend([
        "",
        "## 4. Radial range distribution",
        "",
        "| Range band | Labelled points | Share |",
        "|---|---:|---:|",
    ])
    for label, value in zip(RANGE_LABELS, result["range_counts"]):
        lines.append(f"| {label} | {int(value):,} | {pct(int(value), total)} |")

    lines.extend([
        "",
        "## 5. Effectively absent classes",
        "",
        f"{len(effectively_absent)} of the 64 classes are below 0.01% of all points:",
        "",
        "| ID | Class | Points | Share |",
        "|---:|---|---:|---:|",
    ])
    for key in sorted(effectively_absent, key=lambda k: (counts[k], k)):
        lines.append(
            f"| {key} | {classes[key]} | {int(counts[key]):,} | "
            f"{pct(int(counts[key]), total)} |"
        )

    lines.extend([
        "",
        "## Interpretation boundaries",
        "",
        "- These numbers describe ground-truth label prevalence, not model quality.",
        "- A class absent from a scenario must not be silently treated as IoU zero; "
        "the metric definition must state the included class set.",
        "- Scenario composition is a major confound. Weather and terrain cannot be "
        "separated by comparing the rain and sunny recordings without route matching.",
        "- Sparse points beyond 150 m do not make GOOSE a long-range benchmark.",
        "",
    ])

    out_path = pathlib.Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True, help="Extracted goose_3d_val root")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Markdown output")
    args = parser.parse_args()
    write_report(measure(args.root), args.out)


if __name__ == "__main__":
    main()
