"""Measure the local MAN TruckScenes mini dataset and write a Markdown report."""

from __future__ import annotations

import argparse
import os
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

try:
    from truckscenes import TruckScenes
    from truckscenes.utils.data_classes import LidarPointCloud, RadarPointCloud
except ModuleNotFoundError:  # Allows pure helper tests without the optional devkit.
    TruckScenes = None
    LidarPointCloud = None
    RadarPointCloud = None


CONFIGURED_DATA_ROOT = os.environ.get("TRUCKSCENES_ROOT")
DEFAULT_DATA_ROOT = Path(CONFIGURED_DATA_ROOT) if CONFIGURED_DATA_ROOT else None
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "prepared"
    / "truckscenes-github-package"
    / "TruckScenes - Fatima"
    / "dataset-statistics.md"
)
VERSION = "v1.2-mini"
RANGE_EDGES = [0.0, 25.0, 50.0, 80.0, 100.0, 150.0, float("inf")]
RANGE_LABELS = ["0–25 m", "25–50 m", "50–80 m", "80–100 m", "100–150 m", "150 m+"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", type=Path, default=DEFAULT_DATA_ROOT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def range_counts(points: np.ndarray) -> list[int]:
    radial = np.linalg.norm(points[:2, :], axis=0)
    return [
        int(np.count_nonzero((radial >= low) & (radial < high)))
        for low, high in zip(RANGE_EDGES[:-1], RANGE_EDGES[1:])
    ]


def load_selected_point_stats(trucksc: TruckScenes, data_root: Path) -> list[dict]:
    rows = []
    for index, scene in enumerate(trucksc.scene, start=1):
        sample = trucksc.get("sample", scene["first_sample_token"])
        radar_sd = trucksc.get("sample_data", sample["data"]["RADAR_LEFT_FRONT"])
        lidar_sd = trucksc.get("sample_data", sample["data"]["LIDAR_TOP_FRONT"])
        radar = RadarPointCloud.from_file(str(data_root / radar_sd["filename"]))
        lidar = LidarPointCloud.from_file(str(data_root / lidar_sd["filename"]))
        rows.append(
            {
                "index": index,
                "scene": scene["name"],
                "conditions": scene["description"].replace(";", "; "),
                "sample": sample["token"],
                "annotations": len(sample["anns"]),
                "radar_points": radar.nbr_points(),
                "lidar_points": lidar.nbr_points(),
                "radar_ranges": range_counts(radar.points),
                "lidar_ranges": range_counts(lidar.points),
            }
        )
    return rows


def category_counts(trucksc: TruckScenes) -> Counter:
    instance_category = {item["token"]: item["category_token"] for item in trucksc.instance}
    category_name = {item["token"]: item["name"] for item in trucksc.category}
    result = Counter()
    for ann in trucksc.sample_annotation:
        token = instance_category[ann["instance_token"]]
        result[category_name[token]] += 1
    return result


def scene_annotation_counts(trucksc: TruckScenes) -> Counter:
    sample_to_scene = {sample["token"]: sample["scene_token"] for sample in trucksc.sample}
    scene_name = {scene["token"]: scene["name"] for scene in trucksc.scene}
    result = Counter()
    for ann in trucksc.sample_annotation:
        result[scene_name[sample_to_scene[ann["sample_token"]]]] += 1
    return result


def channel_counts(trucksc: TruckScenes) -> Counter:
    calibrated_to_sensor = {
        item["token"]: item["sensor_token"] for item in trucksc.calibrated_sensor
    }
    sensor_channel = {item["token"]: item["channel"] for item in trucksc.sensor}
    result = Counter()
    for item in trucksc.sample_data:
        sensor_token = calibrated_to_sensor[item["calibrated_sensor_token"]]
        result[sensor_channel[sensor_token]] += 1
    return result


def write_report(trucksc: TruckScenes, selected: list[dict], output: Path) -> None:
    cats = category_counts(trucksc)
    scene_anns = scene_annotation_counts(trucksc)
    channels = channel_counts(trucksc)
    modality_counts = Counter(sensor["modality"] for sensor in trucksc.sensor)
    total_radar = sum(row["radar_points"] for row in selected)
    total_lidar = sum(row["lidar_points"] for row in selected)
    radar_ranges = np.sum([row["radar_ranges"] for row in selected], axis=0).astype(int)
    lidar_ranges = np.sum([row["lidar_ranges"] for row in selected], axis=0).astype(int)
    lidar_to_radar = total_lidar / total_radar if total_radar else float("nan")

    lines = [
        "# MAN TruckScenes v1.2-mini — measured dataset statistics",
        "",
        "**Owner:** Fatima Sher  ",
        "**Measurement scope:** local `v1.2-mini` metadata plus the first annotated sample from each of its 10 scenes  ",
        "**Generated by:** `scripts/truckscenes_stats.py`",
        "",
        "## 1. Dataset inventory",
        "",
        "| Item | Measured value |",
        "|---|---:|",
        f"| Scenes | {len(trucksc.scene):,} |",
        f"| Annotated samples | {len(trucksc.sample):,} |",
        f"| Sample annotations | {len(trucksc.sample_annotation):,} |",
        f"| Instances | {len(trucksc.instance):,} |",
        f"| Categories | {len(trucksc.category):,} |",
        f"| Sample-data records | {len(trucksc.sample_data):,} |",
        f"| Calibrated sensors | {len(trucksc.calibrated_sensor):,} |",
        "",
        "## 2. Sensor inventory",
        "",
        "| Modality | Sensor channels |",
        "|---|---:|",
    ]
    for modality, count in sorted(modality_counts.items()):
        lines.append(f"| {modality} | {count:,} |")
    lines.extend(["", "### Sample-data records by channel", "", "| Channel | Records |", "|---|---:|"])
    for channel, count in sorted(channels.items()):
        lines.append(f"| {channel} | {count:,} |")

    lines.extend(
        [
            "",
            "## 3. Annotation distribution",
            "",
            "These are ground-truth annotation records, not model predictions.",
            "",
            "| Category | Annotation records | Share |",
            "|---|---:|---:|",
        ]
    )
    total_annotations = sum(cats.values())
    for name, count in cats.most_common():
        lines.append(f"| {name} | {count:,} | {count / total_annotations:.2%} |")

    lines.extend(["", "### Annotation records by scene", "", "| Scene | Records |", "|---|---:|"])
    for scene in trucksc.scene:
        lines.append(f"| {scene['name']} | {scene_anns[scene['name']]:,} |")

    lines.extend(
        [
            "",
            "## 4. Ten-scene paired sample measurements",
            "",
            "One first sample was measured per scene using `RADAR_LEFT_FRONT` and `LIDAR_TOP_FRONT`, matching the generated evidence images.",
            "",
            "| # | Scene | Sample annotations | RADAR points | LiDAR points | LiDAR/RADAR |",
            "|---:|---|---:|---:|---:|---:|",
        ]
    )
    for row in selected:
        ratio = row["lidar_points"] / row["radar_points"] if row["radar_points"] else float("nan")
        lines.append(
            f"| {row['index']} | {row['scene']} | {row['annotations']:,} | "
            f"{row['radar_points']:,} | {row['lidar_points']:,} | {ratio:.1f}× |"
        )
    lines.extend(
        [
            "",
            f"Across these 10 selected samples, LiDAR contained **{total_lidar:,} points** and RADAR contained "
            f"**{total_radar:,} points**. LiDAR therefore contained **{lidar_to_radar:.1f}×** as many points in this "
            "specific paired sample set. This is a measured sample result, not a claim about every frame in the dataset.",
            "",
            "## 5. Radial point distribution for the selected samples",
            "",
            "Range is calculated in each sensor frame as `sqrt(x² + y²)`. Counts are summed across the 10 selected samples.",
            "",
            "| Range band | RADAR points | RADAR share | LiDAR points | LiDAR share |",
            "|---|---:|---:|---:|---:|",
        ]
    )
    for label, radar_count, lidar_count in zip(RANGE_LABELS, radar_ranges, lidar_ranges):
        lines.append(
            f"| {label} | {radar_count:,} | {radar_count / total_radar:.2%} | "
            f"{lidar_count:,} | {lidar_count / total_lidar:.2%} |"
        )

    lines.extend(
        [
            "",
            "## 6. Scene conditions represented",
            "",
            "| # | Scene | Conditions | Sample token |",
            "|---:|---|---|---|",
        ]
    )
    for row in selected:
        lines.append(f"| {row['index']} | {row['scene']} | {row['conditions']} | `{row['sample']}` |")

    lines.extend(
        [
            "",
            "## 7. Interpretation and limits",
            "",
            "- The mini dataset and devkit are operational on the tested macOS machine.",
            "- The measured LiDAR samples are substantially denser than the paired RADAR samples.",
            "- The dataset provides synchronized sensor records and ground-truth 3D annotations suitable for later feasibility tests.",
            "- No detection model has been run. These statistics do not measure precision, recall, mAP or model performance.",
            "- The ten point-cloud comparisons use one sample per scene and must not be presented as a full-dataset point-density benchmark.",
            "- RADAR returns beyond 150 m are present in these samples, but point presence alone does not answer the Scope of Work's beyond-150 m object-detection question.",
            "- Cross-dataset numerical comparison with TruckDrive or GOOSE would violate decision D-01 unless differences are clearly stated and the comparison is qualitative.",
            "",
        ]
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(output)


def main() -> None:
    args = parse_args()
    if args.data_root is None:
        raise SystemExit("Provide --data-root or set TRUCKSCENES_ROOT.")
    if TruckScenes is None:
        raise SystemExit("Install truckscenes-devkit before reading the dataset.")
    trucksc = TruckScenes(version=VERSION, dataroot=str(args.data_root), verbose=False)
    selected = load_selected_point_stats(trucksc, args.data_root)
    write_report(trucksc, selected, args.output)


if __name__ == "__main__":
    main()
